version: '3.8'
services:
  tomcat:
    image: 575672604269.dkr.ecr.us-east-1.amazonaws.com/ferp:2025.1.04-24.2.38714-101dd-release-2025.1.04-24
    ports:
      - "8080:8080"
      - "4000:4000"
    environment:
      SCHEDULE_MANAGER: "default"
      TZ: "America/Chicago"
      CATALINA_OPTS: "your_catalina_opts_value_here" # ❗ REPLACE THIS
      DB_PASSWORD: "your_db_password_here"           # ❗ REPLACE THIS
      DB_TYPE: "your_db_type_here"                   # ❗ REPLACE THIS
      DB_URL: "your_db_url_here"                     # ❗ REPLACE THIS
      DB_USER: "your_db_user_here"                   # ❗ REPLACE THIS
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs
      - tomcat_shared:/opt/teams/share/environments/pd
      - tomcat_jasper:/opt/teams/share/jasper
      - tomcat_glowroot_config:/opt/glowroot/glowroot.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/common/SimpleSystemStatusServlet?healthcheck=true"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 120s
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 28000M
volumes:
  tomcat_logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/teams/share/pd/logs'
  tomcat_shared:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/teams/share/environments/pd'
  tomcat_jasper:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/teams/share/environments/pd/jasper'
  tomcat_glowroot_config: # This named volume will point to the file we create
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/glowroot/glowroot.properties' # Host path for the file
