# roles/docker_swarm/tasks/main.yml
---
- name: Check if node is already in a Swarm
  become: true
  ansible.builtin.command: docker info
  register: docker_info
  changed_when: false
  failed_when: false

- name: Set swarm_active fact
  ansible.builtin.set_fact:
    swarm_active: "{{ 'Swarm: active' in docker_info.stdout }}"
  when: docker_info.rc == 0

# --- Master Node Tasks ---
- name: Initialize Docker Swarm on the master node
  become: true
  ansible.builtin.command: >
    docker swarm init --advertise-addr {{ ansible_host }}
  register: swarm_init_result
  when:
    - inventory_hostname in groups['swarm_master']
    - not swarm_active | default(false)
  changed_when: "'Swarm initialized' in swarm_init_result.stdout"

# *** ADDED: Pause briefly after init ***
- name: Pause for 5 seconds after Swarm init
  ansible.builtin.pause:
    seconds: 5
  when:
    # Only pause if init actually ran and changed something
    - inventory_hostname in groups['swarm_master']
    - swarm_init_result.changed | default(false)

- name: Get the worker join token from the master
  become: true
  ansible.builtin.command: docker swarm join-token worker -q
  register: worker_token_result
  when:
    - inventory_hostname in groups['swarm_master']
  changed_when: false

- name: Store worker token and master IP as facts on the master
  ansible.builtin.set_fact:
    swarm_worker_token: "{{ worker_token_result.stdout }}"
    swarm_master_ip: "{{ ansible_host }}"
  when:
    - inventory_hostname in groups['swarm_master']
    - worker_token_result.rc == 0

# --- Worker Node Tasks ---

# *** ADDED: Debugging task ***
- name: Debug Swarm Join Variables (Worker)
  ansible.builtin.debug:
    msg: >-
      Attempting join with Token={{ hostvars[groups['swarm_master'][0]]['swarm_worker_token'] | default('UNDEFINED') }}
      MasterIP={{ hostvars[groups['swarm_master'][0]]['swarm_master_ip'] | default('UNDEFINED') }}
  when:
    - inventory_hostname in groups['swarm_worker']
    - not swarm_active | default(false)

- name: Join worker nodes to the Swarm
  become: true
  ansible.builtin.command: >
    docker swarm join --token {{ hostvars[groups['swarm_master'][0]]['swarm_worker_token'] }} {{ hostvars[groups['swarm_master'][0]]['swarm_master_ip'] }}:2377
  register: swarm_join_result
  when:
    - inventory_hostname in groups['swarm_worker']
    - not swarm_active | default(false)
    - hostvars[groups['swarm_master'][0]]['swarm_worker_token'] is defined
    - hostvars[groups['swarm_master'][0]]['swarm_master_ip'] is defined
  changed_when: "'This node joined a swarm as a worker' in swarm_join_result.stdout"
  failed_when:
    - swarm_join_result.rc != 0
    - "'This node is already part of a swarm' not in swarm_join_result.stderr"


